spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/dev-db
    username: admin
    password: admin
  liquibase:
    enabled: true
    change-log: classpath:db/liquibase/changelog-master.yaml
    contexts: dev
  jpa:
    show-sql: true
    hibernate:
    #      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect